=== Crillojul/GeneradorCV/xml/datos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="generadorcv">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="usuariado">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cuenta" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="apellidos" type="xs:string"/>
                                        <xs:element name="mail" type="xs:string"/>
                                        <xs:element name="user" type="xs:string"/>
                                        <xs:element name="pass" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:integer" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="curriculums">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="CV" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="titulo" type="xs:string"/>
                                        <xs:element name="formacion">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="titulacion" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="nombre" type="xs:string"/>
                                                                <xs:element name="fecha" type="xs:date"/>
                                                                <xs:element name="centro" type="xs:string"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="idioma" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="nombre" type="xs:string"/>
                                                                <xs:element name="nivel" type="xs:string"/>
                                                                <xs:element name="certificado" type="xs:string"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="experiencia">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="item" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="titulo" type="xs:string"/>
                                                                <xs:element name="categoria" type="xs:string"/>
                                                                <xs:element name="descripcion" type="xs:string"/>
                                                                <xs:element name="fecha_inicio" type="xs:date"/>
                                                                <xs:element name="fecha_fin" type="xs:date"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="cuenta" type="xs:integer" use="required"/>
                                    <xs:attribute name="id" type="xs:integer" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Crillojul/GeneradorCV/xml/datos.xml
<?xml version="1.0" encoding="UTF-8"?>
<generadorcv xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datos.xsd"><usuariado><cuenta id="0"><nombre>Administración</nombre><apellidos>verepass</apellidos><mail>admin@verepass.com</mail><user>root</user><pass>123456</pass></cuenta><cuenta id="1"><nombre>Ana</nombre><apellidos>Simón Simón</apellidos><mail>anass@gmail.com</mail><user>anass</user><pass>123456</pass></cuenta><cuenta id="4"><nombre>Cristian</nombre><apellidos>Llorens Julio</apellidos><mail>crisllor@gmail.com</mail><user>cristian1995</user><pass>123456</pass></cuenta></usuariado><curriculums><CV cuenta="1" id="0"><titulo>CV0 Ana Simón</titulo><formacion><titulacion><nombre>Carrera de derecho</nombre><fecha>2018-06-28</fecha><centro>Universidad Publica de Zaragoza</centro></titulacion><idioma><nombre>Español</nombre><nivel>Materno</nivel><certificado/></idioma></formacion><experiencia><item><titulo>Auxiliar de secretario judicial - Aboga2</titulo><categoria>Prácticas</categoria><descripcion>Contrato de prácticas como ayundante de secretario judicial en Aboga2.</descripcion><fecha_inicio>2018-09-06</fecha_inicio><fecha_fin>2020-11-14</fecha_fin></item></experiencia></CV><CV cuenta="1" id="1"><titulo>Curriculum de Ana</titulo><formacion><titulacion><nombre>FP Carpintería</nombre><fecha>2019-06-01</fecha><centro>Centro Carpi</centro></titulacion><idioma><nombre>Español</nombre><nivel>Nativo</nivel><certificado>no</certificado></idioma></formacion><experiencia><item><titulo>Ayudante de carpintería</titulo><categoria>Ayudante</categoria><descripcion>Auxiliar de mi jefe</descripcion><fecha_inicio>6546-05-02</fecha_inicio><fecha_fin>5646-12-05</fecha_fin></item><item><titulo>Ayudante de carpinteria</titulo><categoria>Ayundante</categoria><descripcion>Auxiliar de mi jefe</descripcion><fecha_inicio>5454-05-06</fecha_inicio><fecha_fin>4645-05-06</fecha_fin></item><item><titulo>Carpintero Junior</titulo><categoria>Junior</categoria><descripcion>hacer cosas con madera</descripcion><fecha_inicio>8549-06-06</fecha_inicio><fecha_fin>8846-04-15</fecha_fin></item><item><titulo>Carpintero Senior</titulo><categoria>Senior</categoria><descripcion>Mandar a otros carpinteros</descripcion><fecha_inicio>5584-04-05</fecha_inicio><fecha_fin>4559-04-04</fecha_fin></item></experiencia></CV><CV cuenta="4" id="0"><titulo>Curriculum de Cristian</titulo><formacion><titulacion><nombre>FP Cocina</nombre><fecha>2019-06-21</fecha><centro>Centro Mediterraneo</centro></titulacion><titulacion><nombre>FP Informatica</nombre><fecha>2024-06-21</fecha><centro>IES La Vereda</centro></titulacion><idioma><nombre>Español</nombre><nivel>Nativo</nivel><certificado>Sin certificado</certificado></idioma></formacion><experiencia><item><titulo>Ayudante de cocina</titulo><categoria>Hosteleria</categoria><descripcion>Ayuda en cocina a la hora de pelar, cortar verduras. Limpiaba y envasaba carnes, etc.</descripcion><fecha_inicio>2019-07-13</fecha_inicio><fecha_fin>2022-06-12</fecha_fin></item><item><titulo>Practicas como administrador de sistemas</titulo><categoria>Informatica</categoria><descripcion>Estaba de prácticas en la empresa X como administradior de sistemas.</descripcion><fecha_inicio>2023-08-01</fecha_inicio><fecha_fin>2026-08-15</fecha_fin></item></experiencia></CV><CV cuenta="4" id="1"><titulo>CV Cristian de prueba</titulo><formacion><titulacion><nombre>FP Cocina</nombre><fecha>8886-05-24</fecha><centro>cocinados</centro></titulacion><idioma><nombre>Español</nombre><nivel>Nativo</nivel><certificado>Sin certificado</certificado></idioma></formacion><experiencia><item><titulo>Ayudante de cocina</titulo><categoria>Ayudante</categoria><descripcion>Auxiliar de mi jefe</descripcion><fecha_inicio>4556-05-04</fecha_inicio><fecha_fin>4445-08-04</fecha_fin></item></experiencia></CV></curriculums></generadorcv>

=== Crillojul/GeneradorCV/xml/Copia_seguridad_datos.xml
<?xml version="1.0" encoding="UTF-8"?>
<generadorcv xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datos.xsd">
    <usuariado>
        <cuenta id="0">
            <nombre>Administración</nombre>
            <apellidos>verepass</apellidos>
            <mail>admin@verepass.com</mail>
            <user>root</user>
            <pass>123456</pass>
        </cuenta>
        <cuenta id="1">
            <nombre>Ana</nombre>
            <apellidos>Simón Simón</apellidos>
            <mail>anass@gmail.com</mail>
            <user>anass</user>
            <pass>123456</pass>
        </cuenta>
    </usuariado>
    <curriculums>
        <CV cuenta="1" id="0">
            <titulo>CV Ana Simón</titulo>
            <formacion>
                <titulacion>
                    <nombre>Carrera de derecho</nombre>
                    <fecha>2018-06-28</fecha>
                    <centro>Universidad Publica de Zaragoza</centro>
                </titulacion>
                <idioma>
                    <nombre>Español</nombre>
                    <nivel>Materno</nivel>
                    <certificado></certificado>
                </idioma>
            </formacion>
            <experiencia>
                <item>
                    <titulo>Auxiliar de secretario judicial - Aboga2</titulo>
                    <categoria>Prácticas</categoria>
                    <descripcion>Contrato de prácticas como ayundante de secretario judicial en Aboga2.</descripcion>
                    <fecha_inicio>2018-09-06</fecha_inicio>
                    <fecha_fin>2020-11-14</fecha_fin>
                </item>
            </experiencia>
        </CV>
    </curriculums>
</generadorcv>
